# Generated by Django 2.0.13 on 2020-09-14 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GenerateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'upload not completed'), (1, 'csv output completed'), (2, 'visually confirmed'), (3, 'import_data output completed')])),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MatchedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('brycen_file', models.FileField(upload_to='')),
                ('billing_file', models.FileField(upload_to='')),
                ('created_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisuallyMachedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Staff')),
                ('matched', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.MatchedData')),
            ],
        ),
        migrations.AddField(
            model_name='matcheddata',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
        migrations.AddField(
            model_name='matcheddata',
            name='generated',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.GenerateData'),
        ),
        migrations.AddField(
            model_name='importdata',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
        migrations.AddField(
            model_name='importdata',
            name='visually_matched',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.VisuallyMachedData'),
        ),
    ]
