# Generated by Django 2.0.13 on 2020-10-01 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'upload not completed'), (1, 'csv output completed'), (2, 'visually confirmed'), (3, 'import_data output completed')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='generatedata',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='importdata',
            name='created_file',
        ),
        migrations.RemoveField(
            model_name='importdata',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='matcheddata',
            name='created_file',
        ),
        migrations.AddField(
            model_name='importdata',
            name='impot_data_file',
            field=models.FileField(blank=True, null=True, upload_to='import_data_file/%Y/%m%d/'),
        ),
        migrations.AddField(
            model_name='importdata',
            name='visually_matched_file',
            field=models.FileField(blank=True, null=True, upload_to='visually_matched_file/%Y/%m%d/'),
        ),
        migrations.AddField(
            model_name='matcheddata',
            name='matched_data_file',
            field=models.FileField(blank=True, null=True, upload_to='matched_data_file/%Y/%m%d/'),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='billing_file',
            field=models.FileField(upload_to='billing_file/%Y/%m%d/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='brycen_file',
            field=models.FileField(upload_to='brycen_file/%Y/%m%d/', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='generated',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.GeneratedData'),
        ),
        migrations.AlterField(
            model_name='visuallymacheddata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
        migrations.DeleteModel(
            name='GenerateData',
        ),
    ]
