# Generated by Django 2.0.13 on 2020-10-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201001_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisuallyMachedData',
            new_name='VisuallyMatchedData',
        ),
    ]
