# Generated by Django 2.0.13 on 2020-09-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200917_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='billing_file',
            field=models.FileField(upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='brycen_file',
            field=models.FileField(upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='created_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visuallymacheddata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
    ]
