# Generated by Django 2.0.13 on 2020-10-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201006_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importdata',
            old_name='impot_data_file',
            new_name='import_data_file',
        ),
    ]
