# Generated by Django 2.0.13 on 2020-09-23 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200917_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'upload not completed'), (1, 'csv output completed'), (2, 'visually confirmed'), (3, 'import_data output completed')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),

        migrations.AlterField(
            model_name='importdata',
            name='created_file',
            field=models.FileField(upload_to='import_data_file/'),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='visually_matched_file/'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='billing_file',
            field=models.FileField(upload_to='billing_file/'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='brycen_file',
            field=models.FileField(upload_to='brycen_file/'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='created_file',
            field=models.FileField(blank=True, null=True, upload_to='matched_file/'),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='generated',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.GeneratedData'),
        ),

    ]
