# Generated by Django 2.0.13 on 2020-11-02 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201007_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='import_data_file',
            field=models.FileField(blank=True, null=True, upload_to='import_data_file/%Y/%m%d/', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='visually_matched_file',
            field=models.FileField(blank=True, null=True, upload_to='visually_matched_file/%Y/%m%d/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='matched_data_file',
            field=models.FileField(blank=True, null=True, upload_to='matched_data_file/%Y/%m%d/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
