# Generated by Django 2.0.13 on 2020-12-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201102_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateddata',
            old_name='author',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='importdata',
            old_name='author',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='matcheddata',
            old_name='author',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='author',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='visuallymatcheddata',
            old_name='author',
            new_name='staff',
        ),
    ]
