# Generated by Django 2.0.13 on 2020-12-07 03:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201201_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.IntegerField(choices=[(0, '木パレット'), (1, 'コンテナ交換'), (2, 'コンテナレンタル代'), (3, 'ストレッチフィルム'), (4, '汚泥'), (7, 'スクラップ類'), (9, '一般廃棄物'), (10, '産業廃棄物'), (11, 'マニフェスト'), (12, '廃エレメント'), (13, '廃タイヤ'), (14, '台タイヤ'), (15, '廃クーラント'), (16, '廃油'), (17, '産廃税'), (18, '廃バッテリー')])),
                ('unit', models.IntegerField(choices=[(0, 'kg'), (1, '車'), (2, '式'), (3, '月額'), (4, '立米'), (5, '回'), (6, 'ケース'), (7, '台'), (8, '本'), (9, 'リットル'), (10, '枚'), (12, 'メートル'), (13, '個')])),
                ('agent', models.ManyToManyField(to='app.Agent')),
                ('matched', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.MatchedData')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generateddata',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='place',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='billingdata',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
        migrations.AddField(
            model_name='billingdata',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff'),
        ),
    ]
