# Generated by Django 2.0.13 on 2020-12-08 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matcheddata',
            name='billing_file',
            field=models.FileField(blank=True, null=True, upload_to='billing_file/%Y/%m%d/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
