# Generated by Django 2.0.13 on 2020-12-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201208_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='agent_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
