# Generated by Django 2.0.13 on 2020-12-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201208_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingdata',
            old_name='unit_place',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
    ]
