# Generated by Django 2.0.13 on 2020-12-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201209_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='billing_date',
            field=models.DateField(),
        ),
    ]
