# Generated by Django 2.0.13 on 2020-12-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201211_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='matched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MatchedData'),
        ),
    ]
