# Generated by Django 2.0.13 on 2020-12-29 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201211_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
